FROM python:3.7-alpine
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code

RUN apk update && apk add postgresql-dev gcc g++ musl-dev libxml2-dev libxslt-dev libffi-dev make
RUN pip install pipenv

COPY ./django/Pipfile* /code/
RUN pipenv install --deploy --system

EXPOSE 8000

COPY ./django /code/
