# Generated by Django 2.2.6 on 2019-10-14 17:33

from django.db import migrations, models
import django.db.models.deletion
import minecraftserver.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MinecraftModVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MinecraftVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('download_url', models.URLField()),
                ('release_time', models.DateTimeField()),
            ],
            options={
                'ordering': ('-release_time',),
            },
        ),
        migrations.CreateModel(
            name='MinecraftServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('forge', models.BooleanField()),
                ('droplet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('mods', models.ManyToManyField(related_name='_minecraftserverconfig_mods_+', to='minecraftserver.MinecraftModVersion')),
                ('version', models.ForeignKey(default=minecraftserver.models.default_minecraft_version_id, on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='minecraftserver.MinecraftVersion')),
            ],
        ),
        migrations.AddField(
            model_name='minecraftmodversion',
            name='compatible_with',
            field=models.ManyToManyField(related_name='_minecraftmodversion_compatible_with_+', to='minecraftserver.MinecraftVersion'),
        ),
        migrations.AddField(
            model_name='minecraftmodversion',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minecraftserver.MinecraftMod'),
        ),
        migrations.CreateModel(
            name='ForgeVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('download_url', models.URLField()),
                ('minecraft_version', models.OneToOneField(blank=True, help_text='Supported Minecraft version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forge_version', to='minecraftserver.MinecraftVersion')),
            ],
            options={
                'ordering': ('-minecraft_version__release_time',),
            },
        ),
    ]
