# Generated by Django 2.2.6 on 2019-10-11 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('download_url', models.URLField()),
                ('release_time', models.DateTimeField()),
            ],
            options={
                'ordering': ('-release_time',),
            },
        ),
        migrations.CreateModel(
            name='MinecraftServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eula_accepted', models.BooleanField()),
                ('droplet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='minecraftserver.MinecraftVersion')),
            ],
        ),
        migrations.CreateModel(
            name='ForgeVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('download_url', models.URLField()),
                ('minecraft_version', models.ForeignKey(blank=True, help_text='Supported Minecraft version', null=True, on_delete=django.db.models.deletion.SET_NULL, to='minecraftserver.MinecraftVersion')),
            ],
        ),
    ]
