# Generated by Django 2.2.6 on 2019-10-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minecraftserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forgeversion',
            options={'ordering': ('-minecraft_version__release_time',)},
        ),
        migrations.AddField(
            model_name='minecraftserver',
            name='forge',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forgeversion',
            name='minecraft_version',
            field=models.OneToOneField(blank=True, help_text='Supported Minecraft version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forge_version', to='minecraftserver.MinecraftVersion'),
        ),
        migrations.AlterField(
            model_name='minecraftserver',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='minecraftserver.MinecraftVersion'),
        ),
    ]
