# Generated by Django 2.2.6 on 2019-10-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minecraftserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minecraftmodversion',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='minecraftserver.MinecraftMod'),
        ),
    ]
