# Generated by Django 2.2.6 on 2019-10-11 05:54

from django.db import migrations, models
import django.db.models.deletion
import minecraftserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraftserver', '0002_auto_20191011_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minecraftserver',
            name='version',
            field=models.ForeignKey(default=minecraftserver.models.default_minecraft_version_id, on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='minecraftserver.MinecraftVersion'),
        ),
    ]
