# Generated by Django 2.2.6 on 2019-10-14 21:29

from django.db import migrations, models
import django.db.models.deletion
import minecraftserver.models.minecraft


class Migration(migrations.Migration):

    dependencies = [
        ('minecraftserver', '0003_auto_20191014_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('digitalocean_id', models.PositiveIntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='minecraftserverconfig',
            name='ssh_key',
            field=models.ForeignKey(blank=True, default=minecraftserver.models.minecraft.default_ssh_key, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minecraftserver.KeyPair'),
        ),
    ]
