# Generated by Django 2.2.6 on 2019-10-29 04:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('available', models.BooleanField()),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('available', models.BooleanField()),
                ('transfer', models.FloatField()),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_hourly', models.FloatField()),
                ('memory', models.PositiveIntegerField()),
                ('vcpus', models.PositiveIntegerField()),
                ('disk', models.PositiveIntegerField()),
                ('regions', models.ManyToManyField(blank=True, to='djocean.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_id', models.PositiveIntegerField(unique=True, verbose_name='DigitalOcean ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('snapshot', 'snapshot'), ('backup', 'backup'), ('custom', 'custom')], max_length=20)),
                ('distribution', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('public', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('min_disk_size', models.PositiveIntegerField()),
                ('size_gigabytes', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('available', 'available'), ('pending', 'pending'), ('deleted', 'deleted')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('regions', models.ManyToManyField(blank=True, to='djocean.Region')),
            ],
        ),
    ]
