# Generated by Django 2.2.6 on 2019-10-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djocean', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['price_hourly']},
        ),
    ]
